name: maven build

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: build
        run: mvn --% install -"Dlicensing.skip" --no-transfer-progress

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}

      - name: build
        run: mvn -Dlicensing.skip --no-transfer-progress install
