name: maven build

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}

      - name: build
        run: mvn --no-transfer-progress install

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}

      - name: build
        run: mvn --no-transfer-progress install
